config/routes.rb
ReservationSystem::Application.routes.draw do
    
  resources :reservations

  root :to => "reservations#index"

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
    
    validates :num_guests, :numericality => {:only_integer => true}
    validates :name, :num_guests, :presence => true
    validates :start_time, :presence => true, :allow_blank => false
    validates :table_reserved, :uniqueness => {:scope => :start_time, :message => "Reservation is not available at the requested time"}
    validate :start_time_in_restaurant_hours, :unless => Proc.new { |r| r.start_time.blank? }
    validate :start_time_in_future, :unless => Proc.new { |r| r.start_time.blank? }
    validate :num_guests_less_than_4
    
    # before_create :reserve_table
    after_validation :reserve_table
    
    NUM_GUESTS_UPPER_LIMIT = 4
    START_TIME_LOW_LIMIT = 17      # 5 PM
    START_TIME_UPPER_LIMIT = 20    # 8 PM
    START_WDAY_LOW_LIMIT = 1       # Monday
    START_WDAY_UPPER_LIMIT = 5     # Friday
    TABLE_1_CAPACITY = 2
    TABLE_2_CAPACITY = 4
    
    protected
    
    def num_guests_less_than_4
      if (!(1..NUM_GUESTS_UPPER_LIMIT).include?(num_guests) )
          errors[:base] << "We can only accomadate a maximum of 4 guests"
          errors.add( :start_time, "Please select the number of guests again")
      end
    end
    
    def start_time_in_restaurant_hours
       if (!(START_TIME_LOW_LIMIT..START_TIME_UPPER_LIMIT).include?(start_time.hour) or !(START_WDAY_LOW_LIMIT..START_WDAY_UPPER_LIMIT).include?(start_time.wday))
         errors[:base] << "Please select a time between 5PM & 8PM - Monday to Friday"
         errors.add( :start_time, "The restaurant does not operate at the selected time")
       end
    end
    
    def start_time_in_future
       if (start_time < Time.now)
         errors[:base] << "Please select a valid day/time"
         errors.add( :start_time, "The requested day/time is not valid")
       end
    end
    
    def table_capacity(table_num)
        case table_num.to_i
        when 1
            return TABLE_1_CAPACITY
        when 2
            return TABLE_2_CAPACITY
        end
    end
    
    def current_reservations
        @exis_res = Reservation.where(:start_time => (self.start_time - 59.minutes)...(self.start_time + 2.hours))
    end
    
    def available_tables
       tables = [1,2]
       current_reservations.each do |er|
           if(er.table_reserved.to_i == 1)
               tables.delete(1)
           elsif(er.table_reserved.to_i == 2)
               tables.delete(2)
           end
           break if tables.empty?
       end
       tables
    end
    
    def reserve_table
        if(errors.nil? or errors.empty?)
            avail_tables = available_tables
            case avail_tables.length.to_i
            when 0
                throw_table_unavailable_error
            when 1
                if table_capacity(avail_tables[0].to_i) >= self.num_guests.to_i
                    self.table_reserved = avail_tables[0].to_i
                else
                    throw_table_unavailable_error
                end
            when 2
                if table_capacity(avail_tables[0].to_i) >= self.num_guests.to_i
                    self.table_reserved = avail_tables[0]
                elsif table_capacity(avail_tables[1].to_i) >= self.num_guests.to_i
                    self.table_reserved = avail_tables[1]
                else
                    throw_table_unavailable_error
                end
            end
        end
    end
    
    def throw_table_unavailable_error
        errors[:base] << "This reservation cannot be made because.."
        errors.add( :table_reserved, "No table is available at the requested start time") 
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    
    
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, :notice => 'Reservation was successfully created.' }
        format.json { render :json => @reservation, :status => :created, :location => @reservation }
      else
        format.html { render :action => "new" }
        format.json { render :json => @reservation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, :notice => 'Reservation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @reservation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :ok }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReservationSystem</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.select :num_guests, options_for_select([1,2,3,4]) %><br />
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time ,:start_year => Time.now.year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Listing reservations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Num guests</th>
    <th>Start time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reservations.each do |reservation| %>
  <tr>
    <td><%= reservation.name %></td>
    <td><%= reservation.num_guests %></td>
    <td><%= reservation.start_time %></td>
    <td><%= link_to 'Show', reservation %></td>
    <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
    <td><%= link_to 'Destroy', reservation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @reservation.name %>
</p>

<p>
  <b>Num guests:</b>
  <%= @reservation.num_guests %>
</p>

<p>
  <b>Start time:</b>
  <%= @reservation.start_time %>
</p>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>